DICCIONARIO_SINTOMAS = {
    'itching': 'Picazón',
    'skin_rash': 'Erupción cutánea',
    'nodal_skin_eruptions': 'Erupciones nodulares en la piel',
    'continuous_sneezing': 'Estornudos continuos',
    'shivering': 'Escalofríos',
    'chills': 'Frialdad / Temblores',
    'joint_pain': 'Dolor en las articulaciones',
    'stomach_pain': 'Dolor de estómago',
    'acidity': 'Acidez',
    'ulcers_on_tongue': 'Úlceras en la lengua',
    'muscle_wasting': 'Desgaste muscular',
    'vomiting': 'Vómitos',
    'burning_micturition': 'Ardor al orinar',
    'spotting_ urination': 'Goteo al orinar',
    'fatigue': 'Fatiga',
    'weight_gain': 'Aumento de peso',
    'anxiety': 'Ansiedad',
    'cold_hands_and_feets': 'Manos y pies fríos',
    'mood_swings': 'Cambios de humor',
    'weight_loss': 'Pérdida de peso',
    'restlessness': 'Inquietud',
    'lethargy': 'Letargo',
    'patches_in_throat': 'Manchas en la garganta',
    'irregular_sugar_level': 'Nivel irregular de azúcar',
    'cough': 'Tos',
    'high_fever': 'Fiebre alta',
    'sunken_eyes': 'Ojos hundidos',
    'breathlessness': 'Dificultad para respirar',
    'sweating': 'Sudoración',
    'dehydration': 'Dehidratación',
    'indigestion': 'Indigestión',
    'headache': 'Dolor de cabeza',
    'yellowish_skin': 'Piel amarillenta',
    'dark_urine': 'Orina oscura',
    'nausea': 'Náuseas',
    'loss_of_appetite': 'Pérdida de apetito',
    'pain_behind_the_eyes': 'Dolor detrás de los ojos',
    'back_pain': 'Dolor de espalda',
    'constipation': 'Estreñimiento',
    'abdominal_pain': 'Dolor abdominal',
    'diarrhoea': 'Diarrea',
    'mild_fever': 'Fiebre leve',
    'yellow_urine': 'Orina amarilla',
    'yellowing_of_eyes': 'Ojos amarillentos',
    'acute_liver_failure': 'Insuficiencia hepática aguda',
    'fluid_overload': 'Sobrecarga de líquidos',
    'swelling_of_stomach': 'Hinchazón de estómago',
    'swelled_lymph_nodes': 'Ganglios linfáticos inflamados',
    'malaise': 'Malestar general',
    'blurred_and_distorted_vision': 'Visión borrosa y distorsionada',
    'phlegm': 'Flema',
    'throat_irritation': 'Irritación de garganta',
    'redness_of_eyes': 'Enrojecimiento de los ojos',
    'sinus_pressure': 'Presión en los senos paranasales',
    'runny_nose': 'Secreción nasal',
    'congestion': 'Congestión nasal',
    'chest_pain': 'Dolor de pecho',
    'weakness_in_limbs': 'Debilidad en las extremidades',
    'fast_heart_rate': 'Frecuencia cardíaca rápida',
    'pain_during_bowel_movements': 'Dolor al defecar',
    'pain_in_anal_region': 'Dolor en la región anal',
    'bloody_stool': 'Heces con sangre',
    'irritation_in_anus': 'Irritación en el ano',
    'neck_pain': 'Dolor de cuello',
    'dizziness': 'Mareos',
    'cramps': 'Calambres',
    'bruising': 'Moretones',
    'obesity': 'Obesidad',
    'swollen_legs': 'Piernas hinchadas',
    'swollen_blood_vessels': 'Vasos sanguíneos inflamados',
    'puffy_face_and_eyes': 'Cara y ojos hinchados',
    'enlarged_thyroid': 'Tiroides agrandada',
    'brittle_nails': 'Uñas quebradizas',
    'swollen_extremeties': 'Extremidades hinchadas',
    'excessive_hunger': 'Hambre excesiva',
    'extra_marital_contacts': 'Contactos extramatrimoniales',
    'drying_and_tingling_lips': 'Labios secos y con hormigueo',
    'slurred_speech': 'Habla arrastrada',
    'knee_pain': 'Dolor de rodilla',
    'hip_joint_pain': 'Dolor de cadera',
    'muscle_weakness': 'Debilidad muscular',
    'stiff_neck': 'Cuello rígido',
    'swelling_joints': 'Articulaciones hinchadas',
    'movement_stiffness': 'Rigidez de movimientos',
    'spinning_movements': 'Vértigo',
    'loss_of_balance': 'Pérdida de equilibrio',
    'unsteadiness': 'Inestabilidad',
    'weakness_of_one_body_side': 'Debilidad en un lado del cuerpo',
    'loss_of_smell': 'Pérdida del olfato',
    'bladder_discomfort': 'Malestar en la vejiga',
    'foul_smell_of urine': 'Mal olor de la orina',
    'continuous_feel_of_urine': 'Sensación continua de orinar',
    'passage_of_gases': 'Flatulencia',
    'internal_itching': 'Picazón interna',
    'toxic_look_(typhos)': 'Aspecto tóxico (Tifoidea)',
    'depression': 'Depresión',
    'irritability': 'Irritabilidad',
    'muscle_pain': 'Dolor muscular',
    'altered_sensorium': 'Nivel de conciencia alterado',
    'red_spots_over_body': 'Manchas rojas en el cuerpo',
    'belly_pain': 'Dolor de vientre',
    'abnormal_menstruation': 'Menstruación anormal',
    'dischromic _patches': 'Manchas discrómicas',
    'watering_from_eyes': 'Lagrimeo excesivo',
    'increased_appetite': 'Aumento del apetito',
    'polyuria': 'Poliuria',
    'family_history': 'Antecedentes familiares',
    'mucoid_sputum': 'Esputo mucoide',
    'rusty_sputum': 'Esputo oxidado',
    'lack_of_concentration': 'Falta de concentración',
    'visual_disturbances': 'Alteraciones visuales',
    'receiving_blood_transfusion': 'Transfusión de sangre',
    'receiving_unsterile_injections': 'Inyecciones no estériles',
    'coma': 'Coma',
    'stomach_bleeding': 'Sangrado estomacal',
    'distention_of_abdomen': 'Distensión abdominal',
    'history_of_alcohol_consumption': 'Historial de consumo de alcohol',
    'fluid_overload.1': 'Sobrecarga de líquidos severa',
    'blood_in_sputum': 'Sangre en el esputo',
    'prominent_veins_on_calf': 'Venas prominentes en pantorrilla',
    'palpitations': 'Palpitaciones',
    'painful_walking': 'Dolor al caminar',
    'pus_filled_pimples': 'Espinillas con pus',
    'blackheads': 'Puntos negros',
    'scurring': 'Cicatrices',
    'skin_peeling': 'Descamación de la piel',
    'silver_like_dusting': 'Polvo plateado en la piel',
    'small_dents_in_nails': 'Abolladuras en uñas',
    'inflammatory_nails': 'Uñas inflamadas',
    'blister': 'Ampollas',
    'red_sore_around_nose': 'Llagas rojas alrededor de la nariz',
    'yellow_crust_ooze': 'Costra amarilla'
}

DICCIONARIO_ENFERMEDADES = {
    'Fungal infection': 'Infección Fúngica',
    'Allergy': 'Alergia',
    'GERD': 'Enfermedad por Reflujo Gastroesofágico',
    'Chronic cholestasis': 'Colestasis Crónica',
    'Drug Reaction': 'Reacción a Medicamentos',
    'Peptic ulcer diseae': 'Úlcera Péptica',
    'AIDS': 'VIH/SIDA',
    'Diabetes': 'Diabetes',
    'Gastroenteritis': 'Gastroenteritis',
    'Bronchial Asthma': 'Asma Bronquial',
    'Hypertension': 'Hipertensión',
    'Migraine': 'Migraña',
    'Cervical spondylosis': 'Espondilosis Cervical',
    'Paralysis (brain hemorrhage)': 'Parálisis (Hemorragia Cerebral)',
    'Jaundice': 'Ictericia',
    'Malaria': 'Malaria',
    'Chicken pox': 'Varicela',
    'Dengue': 'Dengue',
    'Typhoid': 'Tifoidea',
    'hepatitis A': 'Hepatitis A',
    'Hepatitis B': 'Hepatitis B',
    'Hepatitis C': 'Hepatitis C',
    'Hepatitis D': 'Hepatitis D',
    'Hepatitis E': 'Hepatitis E',
    'Alcoholic hepatitis': 'Hepatitis Alcohólica',
    'Tuberculosis': 'Tuberculosis',
    'Common Cold': 'Resfriado Común',
    'Pneumonia': 'Neumonía',
    'Dimorphic hemmorhoids(piles)': 'Hemorroides',
    'Heart attack': 'Infarto de Miocardio',
    'Varicose veins': 'Venas Varicosas',
    'Hypothyroidism': 'Hipotiroidismo',
    'Hyperthyroidism': 'Hipertiroidismo',
    'Hypoglycemia': 'Hipoglucemia',
    'Osteoarthristis': 'Osteoartritis',
    'Arthritis': 'Artritis',
    '(vertigo) Paroymsal  Positional Vertigo': 'Vértigo Posicional Paroxístico',
    'Acne': 'Acné',
    'Urinary tract infection': 'Infección del Tracto Urinario',
    'Psoriasis': 'Psoriasis',
    'Impetigo': 'Impétigo'
}